id: get_file_sample_by_hash_-_cylance_protect
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Get File Sample By Hash - Cylance Protect
description: Returns to the war-room a file sample correlating to SHA256 hashes in
  the inputs using Cylance Protect integration
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d947a1c1-7312-4f99-8f56-bfcb4b0c3dfe
    type: start
    task:
      id: d947a1c1-7312-4f99-8f56-bfcb4b0c3dfe
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: bb196c7a-ff84-44c7-81fd-625038a5bcf4
    type: condition
    task:
      id: bb196c7a-ff84-44c7-81fd-625038a5bcf4
      version: -1
      name: Is Cylance V2 Protect enabled?
      description: Checks if the the "Cylance Protect" integration is enabled
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "3"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: modules.brand
                iscontext: true
              right:
                value:
                  simple: Cylance Protect v2
          - - operator: isEqualString
              left:
                value:
                  simple: modules.state
                iscontext: true
              right:
                value:
                  simple: active
          accessor: brand
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: af2e86ff-6413-4cd8-8d5f-799edb0770e6
    type: title
    task:
      id: af2e86ff-6413-4cd8-8d5f-799edb0770e6
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -180,
          "y": 1930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 283e4157-b249-4d36-8a57-c2983a3d61d4
    type: condition
    task:
      id: 283e4157-b249-4d36-8a57-c2983a3d61d4
      version: -1
      name: Do we have a SHA256?
      description: Checks for SHA256 in context
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${inputs.SHA256}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 160,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 2299f146-623b-41cc-8fb4-d2f25faa03ec
    type: regular
    task:
      id: 2299f146-623b-41cc-8fb4-d2f25faa03ec
      version: -1
      name: Get download link from HASH
      description: Downloads the threat (file) attached to a specific SHA256 hash.
      script: '|||cylance-protect-download-threat'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      sha256:
        simple: ${inputs.SHA256}
      threshold: {}
      unzip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 160,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a2dfc6e8-e78a-4cc0-8de5-be4a8c155931
    type: condition
    task:
      id: a2dfc6e8-e78a-4cc0-8de5-be4a8c155931
      version: -1
      name: Did we get a download link?
      description: Checks for a download link in context
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: File
          accessor: DownloadURL
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 160,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: d12daf11-c3b1-4079-8b6d-4bbc6023cc4d
    type: regular
    task:
      id: d12daf11-c3b1-4079-8b6d-4bbc6023cc4d
      version: -1
      name: Download File (ZIP format)
      description: Send an HTTP request to download the zip file
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      body: {}
      filename:
        simple: ${inputs.SHA256}.zip
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        complex:
          root: File
          accessor: DownloadURL
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 160,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 917958d1-9c25-4f8d-84f3-5e272848d939
    type: condition
    task:
      id: 917958d1-9c25-4f8d-84f3-5e272848d939
      version: -1
      name: Did we successfully download the ZIP file?
      description: Checks for ZIP file format in context
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "8"
    scriptarguments:
      extend-context: {}
      value:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: zip
          accessor: EntryID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 160,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 5492c4d0-b0c3-4245-8c14-e43fc3ce553f
    type: regular
    task:
      id: 5492c4d0-b0c3-4245-8c14-e43fc3ce553f
      version: -1
      name: Unzip File
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      scriptName: UnzipFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: zip
              ignorecase: true
          accessor: EntryID
      extend-context: {}
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        complex:
          root: inputs.ZipPassword
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 160,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 1a5cf78a-2b23-487e-8520-980ffc50bdf7
    type: condition
    task:
      id: 1a5cf78a-2b23-487e-8520-980ffc50bdf7
      version: -1
      name: Is Cylance V1 Protect enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "10"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: modules.brand
                iscontext: true
              right:
                value:
                  simple: Cylance Protect
          - - operator: isEqualString
              left:
                value:
                  simple: modules.state
                iscontext: true
              right:
                value:
                  simple: active
          accessor: brand
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -410,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 9a83a232-86f0-419b-8c7d-f441b6f6c46e
    type: condition
    task:
      id: 9a83a232-86f0-419b-8c7d-f441b6f6c46e
      version: -1
      name: Do we have a SHA256?
      description: Checks for SHA256 in context
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "11"
    scriptarguments:
      value:
        simple: ${inputs.SHA256}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: ff2a733d-3622-4d7e-8391-e1418c46a720
    type: regular
    task:
      id: ff2a733d-3622-4d7e-8391-e1418c46a720
      version: -1
      name: Get download link from HASH
      description: Downloads the threat (file) attached to a specific SHA256 hash.
      script: '|||cylance-protect-download-threat'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      sha256:
        simple: ${inputs.SHA256}
      threshold: {}
      unzip: {}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: a5416443-e7db-45d3-86eb-86810cc208d6
    type: condition
    task:
      id: a5416443-e7db-45d3-86eb-86810cc208d6
      version: -1
      name: Did we get a download link?
      description: Checks for a download link in context
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: Cylance
          accessor: Threat.Url
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 98e64df6-7105-455f-8298-9101e96b04a9
    type: regular
    task:
      id: 98e64df6-7105-455f-8298-9101e96b04a9
      version: -1
      name: Download File (ZIP format)
      description: Send an HTTP request to download the zip file
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      body: {}
      filename:
        simple: ${inputs.SHA256}.zip
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        complex:
          root: Cylance
          accessor: Threat.Url
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 1f0dd602-7af3-4cf2-8d52-92fe5ab4ead0
    type: condition
    task:
      id: 1f0dd602-7af3-4cf2-8d52-92fe5ab4ead0
      version: -1
      name: Did we successfully download the ZIP file?
      description: Checks for ZIP file format in context
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "15"
    scriptarguments:
      extend-context: {}
      value:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: zip
          accessor: EntryID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 7e6d9805-2917-46d9-891c-a944aa45b1f8
    type: regular
    task:
      id: 7e6d9805-2917-46d9-891c-a944aa45b1f8
      version: -1
      name: Unzip File
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      scriptName: UnzipFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: zip
              ignorecase: true
          accessor: EntryID
      extend-context: {}
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        complex:
          root: inputs.ZipPassword
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
system: true
view: |-
  {
    "linkLabelsPosition": {
      "10_2_#default#": 0.23,
      "9_2_#default#": 0.17
    },
    "paper": {
      "dimensions": {
        "height": 1945,
        "width": 1160,
        "x": -620,
        "y": 50
      }
    }
  }
inputs:
- key: SHA256
  value:
    complex:
      root: File
      accessor: SHA256
  required: false
  description: The SHA256 hash of the file we want to download
  playbookInputQuery:
- key: ZipPassword
  value:
    simple: infected
  required: true
  description: The password for the zip file
  playbookInputQuery:
outputs:
- contextPath: File
  description: The sample file
  type: unknown
tests:
- Cylance Protect v2 Test
- get_file_sample_by_hash_-_cylance_protect_-_test
fromversion: 5.0.0
